main: dev.zenorigins.ZenOrigins
name: ZenOrigins
version: '${project.version}'
description: An Origins-like plugin for Paper that allows players to choose entity types
authors: [YourName]
website: https://github.com/yourusername/ZenOrigins
api-version: '1.21'

softdepend: [LibsDisguises]

commands:
  origin:
    description: Choose your origin/entity type
    aliases: [origins, entity]
    usage: /<command> [list|choose <origin>|reset]
  zenorigins:
    description: Admin commands for ZenOrigins
    aliases: [zo]
    usage: /<command> [reload|reset <player>]
    permission: zenorigins.admin

permissions:
  zenorigins.use:
    description: Allows players to use origin commands
    default: true
  zenorigins.admin:
    description: Allows access to admin commands
    default: op
  zenorigins.origin.*:
    description: Access to all origins
    default: op
    children:
      zenorigins.origin.human: true
      zenorigins.origin.enderman: true
      zenorigins.origin.blaze: true
      zenorigins.origin.spider: true
      zenorigins.origin.phantom: true
      zenorigins.origin.wolf: true
      zenorigins.origin.cat: true
      zenorigins.origin.bee: true
      zenorigins.origin.villager: true
      zenorigins.origin.slime: true
      zenorigins.origin.drowned: true
      zenorigins.origin.irongolem: true
      zenorigins.origin.witch: true
      zenorigins.origin.piglin: true
      zenorigins.origin.panda: true
      zenorigins.origin.parrot: true
      zenorigins.origin.axolotl: true
      zenorigins.origin.ocelot: true
      zenorigins.origin.mooshroom: true
      zenorigins.origin.chicken: true
      zenorigins.origin.squid: true
      zenorigins.origin.sheep: true
  zenorigins.origin.human:
    description: Access to human origin
    default: true
  zenorigins.origin.enderman:
    description: Access to enderman origin
    default: true
  zenorigins.origin.blaze:
    description: Access to blaze origin
    default: true
  zenorigins.origin.spider:
    description: Access to spider origin
    default: true
  zenorigins.origin.phantom:
    description: Access to phantom origin
    default: true
  zenorigins.origin.wolf:
    description: Access to wolf origin
    default: true
  zenorigins.origin.cat:
    description: Access to cat origin
    default: true
  zenorigins.origin.bee:
    description: Access to bee origin
    default: true
  zenorigins.origin.villager:
    description: Access to villager origin
    default: true
  zenorigins.origin.slime:
    description: Access to slime origin
    default: true
  zenorigins.origin.drowned:
    description: Access to drowned origin
    default: true
  zenorigins.origin.irongolem:
    description: Access to iron golem origin
    default: true
  zenorigins.origin.witch:
    description: Access to witch origin
    default: true
  zenorigins.origin.piglin:
    description: Access to piglin origin
    default: true
  zenorigins.origin.panda:
    description: Access to panda origin
    default: true
  zenorigins.origin.parrot:
    description: Access to parrot origin
    default: true
  zenorigins.origin.axolotl:
    description: Access to axolotl origin
    default: true
  zenorigins.origin.ocelot:
    description: Access to ocelot origin
    default: true
  zenorigins.origin.mooshroom:
    description: Access to mooshroom origin
    default: true
  zenorigins.origin.chicken:
    description: Access to chicken origin
    default: true
  zenorigins.origin.squid:
    description: Access to squid origin
    default: true
  zenorigins.origin.sheep:
    description: Access to sheep origin
    default: true
